<?php

define("WEBFORM_DRAFT_TOKEN", 'webform_draft_anonymous');

/**
 * Implements hook_webform_submission_presave().
 */
function webform_draft_anonymous_webform_submission_presave($node, &$submission) {
  if(empty($submission->draft_authlink) && !empty($submission->is_draft)) {
    $length = 128;
    $submission->draft_authlink = user_password($length);

    setcookie(WEBFORM_DRAFT_TOKEN, $submission->draft_authlink, time() + (86400 * 30), "/");
  }
}

/**
 * Implements hook_webform_draft_alter().
 */
function webform_draft_anonymous_webform_draft_alter(&$sid, $context) {
  if(!empty($_COOKIE) && isset($_COOKIE[WEBFORM_DRAFT_TOKEN])){
    $draft_authlink = $_COOKIE[WEBFORM_DRAFT_TOKEN];
    $sid = webform_draft_anonymous_webform_submissions($context['nid'], $context['uid'], $draft_authlink);
  }
}

function webform_draft_anonymous_webform_submissions($nid, $uid, $draft_authlink) {
  $sid = db_select('webform_submissions')
    ->fields('webform_submissions', array('sid'))
    ->condition('nid', $nid)
    ->condition('uid', $uid)
    ->condition('is_draft', 1)
    ->condition('draft_authlink', $draft_authlink)
    ->orderBy('submitted', 'DESC')
    ->execute()
    ->fetchField();

  return $sid;
}